# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions
name: Build and deploy Python app to Azure Web App - wheely-backend

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'
      - '.github/workflows/backend.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment and install dependencies
        working-directory: ./Backend
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          
      - name: Create .env file from GitHub secrets
        working-directory: ./Backend
        run: |
          echo "AZURE_CHAT_API_URL=${{ secrets.AZURE_CHAT_API_URL }}" >> .env
          echo "AZURE_CHAT_SUBSCRIPTION_KEY=${{ secrets.AZURE_CHAT_SUBSCRIPTION_KEY }}" >> .env
          echo "AZURE_EMBEDDING_URL=${{ secrets.AZURE_EMBEDDING_URL }}" >> .env
          echo "AZURE_EMBEDDING_SUBSCRIPTION_KEY=${{ secrets.AZURE_EMBEDDING_SUBSCRIPTION_KEY }}" >> .env
          echo "AZURE_OPENAI_SERVICE_LINE=${{ secrets.AZURE_OPENAI_SERVICE_LINE }}" >> .env
          echo "AZURE_OPENAI_BRAND=${{ secrets.AZURE_OPENAI_BRAND }}" >> .env
          echo "AZURE_OPENAI_PROJECT=${{ secrets.AZURE_OPENAI_PROJECT }}" >> .env
          echo "AZURE_OPENAI_API_VERSION=${{ secrets.AZURE_OPENAI_API_VERSION }}" >> .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
          echo "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}" >> .env
          echo "EMAIL_SENDER=${{ secrets.EMAIL_SENDER }}" >> .env
          echo "user=${{ secrets.DB_USER }}" >> .env
          echo "password=${{ secrets.DB_PASSWORD }}" >> .env
          echo "host=${{ secrets.DB_HOST }}" >> .env
          echo "port=${{ secrets.DB_PORT }}" >> .env
          echo "dbname=${{ secrets.DB_NAME }}" >> .env
          echo "AZURE_OPENAI_URL=${{ secrets.AZURE_OPENAI_URL }}" >> .env
          echo "AZURE_OPENAI_SUBSCRIPTION_KEY=${{ secrets.AZURE_OPENAI_SUBSCRIPTION_KEY }}" >> .env
          echo "AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME=${{ secrets.AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME }}" >> .env

      - name: Zip backend folder contents for deployment
        working-directory: ./Backend
        run: zip -r ../release.zip ./

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_98411378283E43D8A5D64B1F9CB7B74B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BF8013AD49D94641BC752E0E55F20C63 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6DC8FE32BEB94D6BB3D6F9E675204207 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'wheely-backend'
          slot-name: 'Production'
          package: .
